### ISSUE TITLE
Crash on first graph create

### ISSUE THREAD

**Issue by mjdurham** [RedisLabsModules/RedisGraph#370] opened 2019-02-20 19:02 UTC
When benchmarking redis graph with lots of nodes and properties, we ran into issues where the server would randomly crash on the first graph creation.  We narrowed it down to specific strings cause a seg fault on the server.

Steps to reproduce:
Run docker container: `docker run -p 6379:6379 -it --rm redislabs/redisgraph`
Connect via `redis-cli`
Enter in the following:
```
GRAPH.QUERY test "CREATE (:foo{property0:'value0',property8:'value8',property9:'value8',property10:'value10',property14:'value14',property3:'value3',property4:'value4',property7:'value7',property11:'value11',property13:'value13',property6:'value6',property1:'value1',property2:'value2',property5:'value5',property12:'value12'}),(:foo{property8:'value8',property12:'value12',property14:'value14',property2:'value2',property6:'value6',property7:'value7',property13:'value13',property0:'value0',property1:'value1',property3:'value3',property10:'value10',property4:'value4',property5:'value5',property9:'value8',property11:'value11'}),(:foo{property0:'value0',property9:'value8',property10:'value10',property11:'value11',property8:'value8',property1:'value1',property5:'value5',property6:'value6',property7:'value7',property14:'value14',property2:'value2',property3:'value3',property4:'value4',property12:'value12',property13:'value13'}),(:foo{property11:'value11',property0:'value0',property3:'value3',property7:'value7',property8:'value8',property10:'value10',property4:'value4',property5:'value5',property9:'value8',property1:'value1',property12:'value12',property13:'value13',property14:'value14',property2:'value2',property6:'value6'}),(:foo{property13:'value13',property9:'value8',property3:'value3',property4:'value4',property10:'value10',property0:'value0',property5:'value5',property8:'value8',property12:'value12',property1:'value1',property6:'value6',property7:'value7',property11:'value11',property14:'value14',property2:'value2'}),(:foo{property12:'value12',property14:'value14',property2:'value2',property9:'value8',property11:'value11',property0:'value0',property1:'value1',property3:'value3',property4:'value4',property5:'value5',property10:'value10',property6:'value6',property7:'value7',property8:'value8',property13:'value13'}),(:foo{property3:'value3',property5:'value5',property6:'value6',property11:'value11',property12:'value12',property1:'value1',property4:'value4',property7:'value7',property8:'value8',property10:'value10',property14:'value14',property0:'value0',property2:'value2',property9:'value8',property13:'value13'})"
```

Oddly enough, if we run the same test with different ordered properties... it works
```
GRAPH.QUERY test "CREATE (:foo{property11:'value11',property1:'value1',property4:'value4',property5:'value5',property7:'value7',property10:'value10',property3:'value3',property6:'value6',property8:'value8',property9:'value8',property2:'value2',property12:'value12',property14:'value14',property0:'value0',property13:'value13'}),(:foo{property6:'value6',property11:'value11',property0:'value0',property3:'value3',property4:'value4',property8:'value8',property10:'value10',property1:'value1',property5:'value5',property7:'value7',property13:'value13',property2:'value2',property9:'value8',property12:'value12',property14:'value14'}),(:foo{property4:'value4',property7:'value7',property8:'value8',property10:'value10',property12:'value12',property6:'value6',property11:'value11',property14:'value14',property0:'value0',property2:'value2',property3:'value3',property5:'value5',property9:'value8',property1:'value1',property13:'value13'}),(:foo{property11:'value11',property0:'value0',property3:'value3',property10:'value10',property12:'value12',property14:'value14',property1:'value1',property4:'value4',property6:'value6',property8:'value8',property9:'value8',property13:'value13',property2:'value2',property5:'value5',property7:'value7'}),(:foo{property6:'value6',property9:'value8',property0:'value0',property1:'value1',property2:'value2',property8:'value8',property10:'value10',property12:'value12',property4:'value4',property5:'value5',property7:'value7',property11:'value11',property13:'value13',property3:'value3',property14:'value14'}),(:foo{property5:'value5',property10:'value10',property2:'value2',property3:'value3',property7:'value7',property8:'value8',property12:'value12',property11:'value11',property13:'value13',property14:'value14',property0:'value0',property1:'value1',property4:'value4',property6:'value6',property9:'value8'}),(:foo{property4:'value4',property5:'value5',property8:'value8',property9:'value8',property10:'value10',property12:'value12',property0:'value0',property3:'value3',property7:'value7',property11:'value11',property13:'value13',property1:'value1',property14:'value14',property6:'value6',property2:'value2'})"
``` 

If you enter the second string in first and then the first, nothing crashes

**Comment by mjdurham** [comment] 2019-02-20 19:04
Just entering in the first 2 nodes causes it to fail as well (this is a shorter string):
```
GRAPH.QUERY test "CREATE (:foo{property11:'value11',property1:'value1',property4:'value4',property5:'value5',property7:'value7',property10:'value10',property3:'value3',property6:'value6',property8:'value8',property9:'value8',property2:'value2',property12:'value12',property14:'value14',property0:'value0',property13:'value13'}),(:foo{property6:'value6',property11:'value11',property0:'value0',property3:'value3',property4:'value4',property8:'value8',property10:'value10',property1:'value1',property5:'value5',property7:'value7',property13:'value13',property2:'value2',property9:'value8',property12:'value12',property14:'value14'})"
```

Output from docker:
```
1:C 20 Feb 2019 19:02:53.794 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 20 Feb 2019 19:02:53.794 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 20 Feb 2019 19:02:53.794 # Configuration loaded
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 5.0.3 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

1:M 20 Feb 2019 19:02:53.795 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 20 Feb 2019 19:02:53.795 # Server initialized
1:M 20 Feb 2019 19:02:53.795 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 20 Feb 2019 19:02:53.797 * <graph> Thread pool created, using 4 threads.
1:M 20 Feb 2019 19:02:53.797 * Module 'graph' loaded from /usr/lib/redis/modules/redisgraph.so
1:M 20 Feb 2019 19:02:53.797 * Ready to accept connections


=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 20 Feb 2019 19:03:17.363 # Redis 5.0.3 crashed by signal: 11
1:M 20 Feb 2019 19:03:17.363 # Crashed running the instruction at: 0x7fbf57369c64
1:M 20 Feb 2019 19:03:17.363 # Accessing address: (nil)
1:M 20 Feb 2019 19:03:17.363 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/usr/lib/redis/modules/redisgraph.so(Schema_GetAttributeID+0x34)[0x7fbf57369c64]

Backtrace:
redis-server *:6379(logStackTrace+0x37)[0x5619422a2d57]
redis-server *:6379(sigsegvHandler+0xb0)[0x5619422a3480]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110c0)[0x7fbf59b200c0]
/usr/lib/redis/modules/redisgraph.so(Schema_GetAttributeID+0x34)[0x7fbf57369c64]
/usr/lib/redis/modules/redisgraph.so(Schema_AddAttribute+0x34)[0x7fbf57369cf4]
/usr/lib/redis/modules/redisgraph.so(OpCreateConsume+0x5ee)[0x7fbf5735b4be]
/usr/lib/redis/modules/redisgraph.so(ExecutionPlan_Execute+0x1e)[0x7fbf57356d7e]
/usr/lib/redis/modules/redisgraph.so(_MGraph_Query+0x25d)[0x7fbf5735550d]
/usr/lib/redis/modules/redisgraph.so(+0x7a024)[0x7fbf5736c024]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7fbf59b16494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fbf59858acf]

------ INFO OUTPUT ------
# Server
redis_version:5.0.3
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:9e58cc62e6e78bea
redis_mode:standalone
os:Linux 4.9.125-linuxkit x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:6.3.0
process_id:1
run_id:a14087b833fbb134008488e4f6441c7493751ff7
tcp_port:6379
uptime_in_seconds:24
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:7185525
executable:/data/redis-server
config_file:

# Clients
connected_clients:1
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:1

# Memory
used_memory:1988272
used_memory_human:1.90M
used_memory_rss:5312512
used_memory_rss_human:5.07M
used_memory_peak:1988272
used_memory_peak_human:1.90M
used_memory_peak_perc:251.64%
used_memory_overhead:840742
used_memory_startup:790976
used_memory_dataset:1147530
used_memory_dataset_perc:95.84%
allocator_allocated:938144
allocator_active:1101824
allocator_resident:3612672
total_system_memory:2095869952
total_system_memory_human:1.95G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.17
allocator_frag_bytes:163680
allocator_rss_ratio:3.28
allocator_rss_bytes:2510848
rss_overhead_ratio:1.47
rss_overhead_bytes:1699840
mem_fragmentation_ratio:6.72
mem_fragmentation_bytes:4522392
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:49694
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:1
rdb_bgsave_in_progress:0
rdb_last_save_time:1550689373
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:1
total_commands_processed:1
instantaneous_ops_per_sec:0
total_net_input_bytes:652
total_net_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:1
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:a21bc9b365cf98b2047a6a68fc43b34db1757e40
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.100000
used_cpu_user:0.040000
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Commandstats
cmdstat_graph.QUERY:calls=1,usec=115,usec_per_call=115.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=3 addr=172.17.0.1:37996 fd=8 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY

------ REGISTERS ------
1:M 20 Feb 2019 19:03:17.365 # 
RAX:0000000000000000 RBX:00005619434344d0
RCX:00007fbf575dc578 RDX:00000000ffffffff
RDI:00007fbf50001f80 RSI:00005619434344d0
RBP:00007fbf54f3b000 RSP:00007fbf572ef400
R8 :0000000000000000 R9 :000000000000000a
R10:0000000000000009 R11:0000000000000000
R12:00007fbf54f3b080 R13:0000000000000000
R14:000000000000001c R15:00007fbf572ef4b8
RIP:00007fbf57369c64 EFL:0000000000010293
CSGSFS:002b000000000033
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef40f) -> 00007fbf54e1f000
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef40e) -> 00007fbf500019a0
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef40d) -> 0000000000000008
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef40c) -> 00007fbf572ef4b0
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef40b) -> 00007fbf5735b4be
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef40a) -> 00007fbf572ef4b8
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef409) -> 000000000000001c
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef408) -> 00007fbf54f3b080
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef407) -> 000000000000001e
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef406) -> 00007fbf500018a0
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef405) -> 0000561943434900
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef404) -> 00007fbf500018a0
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef403) -> 00007fbf57369cf4
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef402) -> 00007fbf500018a0
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef401) -> 00005619434344d0
1:M 20 Feb 2019 19:03:17.365 # (00007fbf572ef400) -> 0000000000000138

------ FAST MEMORY TEST ------
1:M 20 Feb 2019 19:03:17.365 # Bio thread for job type #0 terminated
1:M 20 Feb 2019 19:03:17.366 # Bio thread for job type #1 terminated
1:M 20 Feb 2019 19:03:17.366 # Bio thread for job type #2 terminated
*** Preparing to test memory region 5619425d8000 (2248704 bytes)
*** Preparing to test memory region 56194341b000 (135168 bytes)
*** Preparing to test memory region 7fbf50000000 (135168 bytes)
*** Preparing to test memory region 7fbf54e00000 (4194304 bytes)
*** Preparing to test memory region 7fbf552ef000 (8388608 bytes)
*** Preparing to test memory region 7fbf55af0000 (8388608 bytes)
*** Preparing to test memory region 7fbf562f1000 (8388608 bytes)
*** Preparing to test memory region 7fbf56af2000 (8388608 bytes)
*** Preparing to test memory region 7fbf575fc000 (4096 bytes)
*** Preparing to test memory region 7fbf575fe000 (8388608 bytes)
*** Preparing to test memory region 7fbf57dff000 (8388608 bytes)
*** Preparing to test memory region 7fbf58600000 (8388608 bytes)
*** Preparing to test memory region 7fbf58e00000 (8388608 bytes)
*** Preparing to test memory region 7fbf59b0b000 (16384 bytes)
*** Preparing to test memory region 7fbf59d28000 (16384 bytes)
*** Preparing to test memory region 7fbf5a654000 (24576 bytes)
*** Preparing to test memory region 7fbf5a65c000 (12288 bytes)
*** Preparing to test memory region 7fbf5a661000 (4096 bytes)
```

**Comment by jeffreylovitz** [comment] 2019-02-20 20:05
@mjdurham That was an excellent writeup, thank you!

This was caused by an error in the schema lookup routines, a fix should be merged shortly.

**Closed** 2019-02-21 06:29 UTC
